import { Heart } from "lucide-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Button } from "@/ui/components/button";
import { SearchInputText } from "@/ui/components/search-input-text";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-full flex-col items-center">
          <header className="relative w-full border-b">
            <div className="container grid grid-cols-2">
              <SearchInputText className="my-4" placeholder="Buscar usuário" />
            </div>

            <div className="absolute bottom-0 right-0 top-0">
              <Button className="h-full">
                <Heart />
                Favoritos
              </Button>
            </div>
          </header>

          <div className="container flex-1 py-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
